### Numpy
NumPy arrays are fixed-size containers of items that are more efficient than
Python lists or tuples for data processing
- They only store a single data type (mixed data types are stored as a string)
- They can be one dimensional or multi-dimensional
- Array elements can be modified, but the array size cannot change

In [ ]:
import numpy as np

In [ ]:
price = np.array([23, 32, 19, 23, 17, 20, 28, 12, 16, 25])
price

array([23, 32, 19, 23, 17, 20, 28, 12, 16, 25])

#### ARRAY PROPERTIES
The main properties of an array are:
- ndim: the number of dimensions (axes) in the array
- shape: the size of the array for each dimension
- size: the total number of elements in the array
- dtype: the data type of the elements in the array

In [ ]:
price.shape

(10,)

In [ ]:
price.ndim

1

In [ ]:
price.size

10

In [ ]:
price.dtype

dtype('int64')

#### Array Creation
Array can be created using functions such as:
1. **ones**- Creates an array of ones of a given size, as float by default.
  - `np.ones((rows, cols), dtype)`
2. **zeros**- Creates an array of zeros of a given size, as float by default
  - `np.zeros((rows, cols), dtype)`
3. **identity**- Creates an array of a specified size of unit matrix.
  - `np.identity(n, dtype)`
4. **arange**- Creates an array of integers with given start & stop values, and a stepsize (only stop is required, and is not inclusive)
  - `np.arange(start, stop, step)`
5. **linspace**- Creates an array of floats with given start & stop values with n elements, separated by a consistent step size (stop is inclusive)
  - `np.linspace(start, stop, n)`
6. **reshape**- Changes an array into the specified dimensions, if compatible
  - `np.array.reshape(rows, cols)`

In [ ]:
zeros = np.zeros((3, 5), dtype=int)
print(zeros)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
ones = np.ones(4, )
print(ones)

[1. 1. 1. 1.]


In [ ]:
identity = np.identity(3, dtype=int)
print(identity)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
arr_2d = np.arange(1, 10).reshape(3, 3)
arr_2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d.shape

(3, 3)

#### Random Number Arrays
You can create random number arrays from a variety of distributions using
NumPy functions and methods (great for sampling and simulation!)

1. **default.rng**: Creates a random number generator (the seed is for reproducibility) `np.default_rng(seed)`
2. **random**: Returns n random numbers from a uniform distribution between 0 and 1 `rng.random(n)`
3. **normal**: Returns n random numbers from a normal distribution with a given mean and standard deviation `rng.normal(mean, stdev, n)`

In [2]:
import numpy as np

In [ ]:
rng = np.random.default_rng(42)
rng.random(10)

array([0.77395605, 0.43887844, 0.85859792, 0.69736803, 0.09417735,
       0.97562235, 0.7611397 , 0.78606431, 0.12811363, 0.45038594])

In [ ]:
rng.integers(0, 10, 100).reshape(10,10)

array([[4, 6, 6, 4, 8, 5, 0, 7, 5, 6],
       [5, 5, 0, 5, 7, 3, 6, 0, 3, 4],
       [9, 2, 2, 4, 9, 8, 0, 2, 8, 0],
       [8, 2, 9, 2, 4, 6, 1, 5, 5, 7],
       [9, 6, 4, 4, 4, 8, 3, 1, 3, 0],
       [1, 0, 7, 7, 6, 4, 7, 1, 9, 5],
       [9, 1, 4, 6, 4, 4, 1, 3, 2, 3],
       [6, 6, 6, 3, 9, 0, 3, 1, 3, 9],
       [3, 9, 4, 6, 4, 2, 7, 9, 2, 7],
       [2, 7, 7, 4, 7, 2, 0, 0, 4, 9]])

#### Indexing and Slicing

In [17]:
integer_array = np.arange(12)
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
integer_array[2]

2

In [19]:
integer_array[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
integer_array[-1]

11

In [21]:
integer_array[-4:]

array([ 8,  9, 10, 11])

In [22]:
integer_array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [23]:
integer_array[2:9]

array([2, 3, 4, 5, 6, 7, 8])

In [24]:
arr_2d = integer_array.reshape(3,4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
arr_2d[2]

array([ 8,  9, 10, 11])

In [26]:
arr_2d[1, 2]

6

In [28]:
arr_2d[:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [30]:
arr_2d[1:, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
arr_2d[:, 3]

array([ 3,  7, 11])

In [34]:
arr = np.array([[1,2,3],[5,4,6], [-1,-0,8]])
arr

array([[ 1,  2,  3],
       [ 5,  4,  6],
       [-1,  0,  8]])

In [35]:
arr_by2 = arr * 2
arr_by2

array([[ 2,  4,  6],
       [10,  8, 12],
       [-2,  0, 16]])